logging:
  level:
    com.deguru: trace
jwt:
  key: ${password}
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${postgresql.url}
    username: ${postgresql.username}
    password: ${postgresql.password}
    hikari:
      maximum-pool-size: 20
springdoc:
  api-docs:
    path: /v3/api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /index.html
    enabled: true
