logging:
  level:
    com.deguru: trace
jwt:
  key: ${password}
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${postgresql.url}
    username: ${postgresql.username}
    password: ${postgresql.password}
    hikari:
      maximum-pool-size: 20
springdoc:
  swagger-ui:
    layout: BaseLayout